name: "Don't Deploy on Friday!"
description: "Blocks your GitHub deployment from running on Fridays (or any day you like)"
branding:
  icon: calendar
  color: red
inputs:
  day:
    description: 'The day of the week to block deployment on, in Unix calendar.'
    required: false
    default: '5'
runs:
  using: "composite"
  steps:
    - run: bash ${{ github.action_path }}/dont-deploy-on-fridays.sh
      shell: bash
